# Generated by Django 2.2.1 on 2020-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.IntegerField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': True,
            },
        ),
    ]
