# Generated by Django 2.2.1 on 2020-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
